builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: "{{ incpatch .Version }}-next"
archives:
  - files:
      - src: scripts/docker-credential-gcloud
        dst: "."
        strip_parent: true
      - src: scripts/gke-gcloud-auth-plugin
        dst: "."
        strip_parent: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"
